config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    get 'searchwindows/index',as: "search"
  end
  namespace :admin do
    get 'searchwindow/index'
    get 'searchwindow/search'
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
  }

  scope module: :customer do
    resources :addresses, except:[:new,:show]
  end

  scope module: :customer do
    resources :cart_items, except:[:show,:new]
    get 'cart_items/confirm'
  end

  scope module: :customer do
    resources :cart_items, except:[:show,:new]
    delete 'cart_items', to: 'cart_items#all_destroy'
  end

  scope module: :customer do
    get 'orders/thanks', to: 'orders#thanks',as: 'orders_thanks'
    resources :orders, only:[:show,:index,:create]
  end

  scope module: :customer do
    resources :items, only:[:show]
  end

  scope module: :customer do
    get 'customers/with_draw' => "customers#with_draw"
    resources :customers, only:[:show,:edit,:update,:destroy]
  end

  scope module: :home do
    root 'homes#top'
    get 'homes/about'
    get 'homes/category/:id' => "homes#category",as:'category'
  end

  namespace :admin do
    get 'period_index' => 'orders#period_index'
    get 'customer_index/:id' => 'orders#customer_index'
    resources :orders, except:[:new,:show,:create,:destroy] do
      
      patch 'item_update/:order_item_id' => 'orders#item_update', as: 'update'
      put 'item_update/:order_item_id' => 'orders#item_update'
    end
  end

  namespace :admin do
    resources :items
  end

  namespace :admin do
    resources :customers, only:[:index,:show,:edit,:update]
    get 'customer/top' => "customers#top"
  end

  namespace :admin do
    resources :categories
  end

  namespace :admin do
  get "searches/" => "searchwindows#index", as: "search"
  end

  namespace :admin do
  get "customer/searches/" => "customersearches#index"
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :addresses
	has_many :cart_items
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を漢字、ひらがな、カタカナで入力してください" }
  validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を漢字、ひらがな、カタカナで入力してください"}
  validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "をカタカナで入力してください"}
  validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "をカタカナで入力してください"}
  validates :postal_code, format: { with: /\A[0-9０-９]+\z/,  message: "を数値で入力してください"}
  validates :address, presence: true
  validates :tel, format: { with: /\A[0-9０-９]+\z/, message: "を数値で入力してください"} 
  # validates :customer_status, inclusion: {in: [true, false]}
  def active_for_authentication?
    super && customer_status?
  end
  def inactive_message
    customer_status? ? super : :with_draw
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::AdminapplicationsController
  def top
    range = Date.today.beginning_of_day..Date.today.end_of_day
    @order_counts = Order.where(created_at: range)
    @start_time = ""
    @end_time = ""
    # @order_counts = Order.where("created_at between '#{Date.today} 0:00:00' and '#{Date.today} 23:59:59'")
    # @order_counts = Order.where(created_at: 1.day.ago.all_day)
    
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    	flash[:notice] = "You have updated customerstatus successfully."
    	redirect_to admin_customer_path
    else
      flash[:notice] = "You dont have updated customerstatus successfully."
    @customer = Customer.find(params[:id])
    render 'edit'
   end
  end

  private
  def customer_params
     params.require(:customer).permit(:customer_id,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:tel,:email,:customer_status)
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < Customer::CustomerapplicationsController
  before_action :current_customer

  def edit
    @address = Address.find(params[:id])
    
  end


  def index
    @addresses = current_customer.addresses
        # @addresses = Address.where(customer_id :current_customer.id)
    @address_new = Address.new
  end

  def create
    @addresses = current_customer.addresses
    @address_new = Address.new(address_params)
    # @address_new = Address.new
    @address_new.customer_id = current_customer.id
    if  @address_new.save
      flash[:notice] = "配送先を新規登録しました"
      redirect_to addresses_path
    else
 	    render :index
    end
  end

  def update
    @address = Address.find(params[:id])
    @address.customer_id = current_customer.id
    if @address.update(address_params)
      flash[:notice] = "配送先の内容を更新しました"
      redirect_to addresses_path
    else
      render :edit
    end
  end

  def destroy
    address = Address.find(params[:id])
	  address.customer_id = current_customer.id
    address.destroy
    flash[:notice] = "配送先を削除しました"
	  redirect_to addresses_path
  end
end
private
    def address_params
        params.require(:address).permit(:postal_code, :address, :full_name)
    end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < Customer::CustomerapplicationsController
  def edit
  end

  def index
    @customer = current_customer
    @cart_items = @customer.cart_items
    @total = 0
  end

  def confirm
    @customer_id = current_customer.id
    @cart_items = current_customer.cart_items
    @shipping_fee = 800  ##ここ送料！！
    @total_price = 0
    @total_count = 0
    if params[:pay_method].to_i == 0
      @pay_method = "クレジットカード"
    else @pay_method = "現金振込み"
    end
    if params[:name].to_i == 0
      @postal_code = current_customer.postal_code
      @address = current_customer.address
      @full_name = current_customer.last_name + current_customer.first_name
    elsif params[:name].to_i == 1
      selected = Address.find(params[:address_id])
      @postal_code = selected.postal_code
      @address = selected.address
      @full_name = selected.full_name
    else
      @postal_code = params[:postal_code].to_i
      @address = params[:address]
      @full_name = params[:full_name]
    end
  end


def create
  @customer = current_customer
  @cart_items = @customer.cart_items
  x = 0
  @cart_items.each do |cart_item|
    if cart_item.item_id == params[:cart_item][:item_id].to_i
      cart_item.count += params[:cart_item][:count].to_i
      cart_item.save!
      x =1
    end
  end
  if x == 0
     @add_cart_item = CartItem.new(cartitem_params)
     @add_cart_item.save!
   end
  redirect_to cart_items_path
end

  def edit
    @order = Order.new
    @customer = current_customer
    @name =  @customer.last_name + @customer.first_name
    @addresses = current_customer.addresses

  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cartitem_params)
      flash[:notice] = "変更されました!"
      redirect_to cart_items_path
    else
      redirect_to cart_items_path
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end
  def all_destroy
    @customer = current_customer
    @cart_items = @customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
  end
end

private
  def cartitem_params
      params.require(:cart_item).permit(:customer_id, :item_id, :count)
  end

app/controllers/customer/customerapplications_controller.rb
class Customer::CustomerapplicationsController < ApplicationController
  # layout 'customers'

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < Customer::CustomerapplicationsController
  before_action :current_customer
  def show
    
  end

  def edit

  end

  def with_draw
  end

  def update
    if current_customer.update(customer_params)
      flash[:notice] = "登録情報の編集が完了しました"
      redirect_to customer_path
    else
      render :edit
    end
  end

  def destroy
      current_customer.update(customer_status: false)
      # current_customer.update(customer_params)
      flash[:notice] = "ご利用いただきまして誠にありがとうございました"
      redirect_to destroy_customer_session_path, method: :delete
  end

private
  def customer_params
    params.require(:customer).permit(:first_name,:last_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:tel,:customer_status)
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < Customer::CustomerapplicationsController
  def show
  	@customer = current_customer
    @item = Item.find(params[:id])
    @cartitem_new = CartItem.new
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < Customer::CustomerapplicationsController
  before_action :current_customer
  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
  end

  def index
    @orders = current_customer.orders
  end

  def thanks
  end

  def create
    if params[:order][:pay_method] == "クレジットカード"
      params[:order][:pay_method] = 0
      order_params[:pay_method] = params[:order][:pay_method]
      else
        params[:order][:pay_method] = 1
        order_params[:pay_method] = params[:order][:pay_method]
    end
    @order = Order.new(order_params)
    if @order.save
      @cart_items = current_customer.cart_items
       @cart_items.each do |cart_item|
        @order_item = OrderItem.new
        @order_item.order_id = @order.id
        @order_item.item_id = cart_item.item_id
        @order_item.price = cart_item.item.price
        @order_item.count = cart_item.count
        @order_item.subtotal = (cart_item.item.price*1.1).round(0)*cart_item.count
        @order_item.save
       end
       CartItem.where(customer_id: current_customer.id).destroy_all
       redirect_to orders_thanks_path
    else redirect_to cart_items_path
    end
  end

  private
  def order_params
      params.require(:order).permit(:customer_id, :postal_code, :address, :full_name, :order_status, :shipping_fee,:total_price, :item_count, :pay_method)
  end
end

app/controllers/customer/searchwindows_controller.rb
class Customer::SearchwindowsController < Customer::CustomerapplicationsController
  def index
    path = Rails.application.routes.recognize_path(request.referer)
    if params[:search] == "" || params[:search] == nil
    redirect_to controller: path[:controller], action: path[:action]
    else
      split_keyword = params[:search].split(/[[:blank:]]+/)
      @items = []
      split_keyword.each do |search|
    next if search == ""
      @items += Item.where('name LIKE(?)', "%#{search}%")
      end
      @items.uniq!
    end
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  layout 'customer'

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'customer'

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  layout 'customer'

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  layout 'customer'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  layout 'customer'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  layout 'customer'

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customerapplications_helper.rb
module Customer::CustomerapplicationsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ながのCAKE-顧客情報編集-</title>
    </head>
    <body>
        <div class="container">
            <% if flash[:notice] %>
                <p><%= flash[:notice] %></p>
            <% end %>

            <h2 class="customertitle">会員編集画面</h2>
            <%= form_for (@customer), url:admin_customer_path do |f| %>
            <div class="col-md-8 col-md-offset-2">
                <table class="table table-fover" frame="box">
                    <tr>
                        <th>顧客ID</th>
                        <td><%= @customer.id %></td>
                    </tr>
                    <tr>
                        <th>氏名</th>
                        <td><%= f.text_field :last_name %>
                            <%= f.text_field :first_name %></td>
                    </tr>
                    <tr>
                        <th>フリガナ</th>
                        <td><%= f.text_field :last_name_kana %>
                            <%= f.text_field :first_name_kana %></td>
                    </tr>
                    <tr>
                        <th>郵便番号</th>
                        <td><%= f.text_field :postal_code %></td>
                    </tr>
                    <tr>
                        <th>住所</th>
                        <td><%= f.text_field :address %></td>
                    </tr>
                    <tr>
                        <th>電話番号</th>
                        <td><%= f.text_field :tel %></td>
                    </tr>
                    <tr>
                        <th>メールアドレス</th>
                        <td><%= f.text_field :email %></td>
                    </tr>
                    <tr>
                        <th>会員ステータス</th>
                        <td>
                            <label><%= f.radio_button :customer_status, true %>
                                有効</label>
                            <label>
                                <%= f.radio_button :customer_status, false %>
                                退会済み</label>
                        </td>
                    </tr>
                </table>
                <%= f.submit '変更を保存する', class:"btn btn-primary glyphicon glyphicon-wrench
                btn-lg" %>
                <% end %>
            </div>
        </div>
    </body>
</html>

app/views/admin/customers/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ながのCAKE-顧客一覧-</title>
    </head>
    <body>
        <div class="container">
            <div class="col-md-8 col-md-offset-2">
                <h2 class="customertitle">会員一覧</h2>
                <table class="table table-fover">
                    <tr>
                        <th>会員ID</th>
                        <th>氏名</th>
                        <th>メールアドレス</th>
                        <th>ステータス</th>
                    </tr>
                    <tbody>
                        <% @customers.each do |customer| %>
                            <tr>
                                <td><%= customer.id %></td>
                                <td><%= link_to customer.last_name + customer.first_name,
                                    admin_customer_path(customer)%></td>
                                <td><%= customer.email %></td>
                                <td>
                                    <% if customer.customer_status == true %>
                                        <p>有効</p>
                                    <% else %>
                                        <p>退会済み</p>
                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <%= paginate @customers %>
            </div>
        </div>
    </body>
</html>

app/views/admin/customers/show.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ながのCAKE-顧客情報詳細-</title>
    </head>
    <body>
        <div class="container">
            <% if flash[:notice] %>
                <p><%= flash[:notice] %></p>
            <% end %>

            <div class="col-md-8 col-md-offset-2">
                <h2 class="customertitle">会員詳細</h2>
                <table class="table table-fover" frame="box">
                    <tr>
                        <th>顧客ID</th>
                        <td><%= @customer.id %>
                            <% if @customer.customer_status == true %>
                                <p>有効</p>
                            <% else %>
                                <p>退会済み</p>
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <th>氏名</th>
                        <td><%= @customer.last_name + @customer.first_name %></td>
                    </tr>
                    <tr>
                        <th>フリガナ</th>
                        <td><%= @customer.first_name_kana + @customer.last_name_kana %></td>
                    </tr>
                    <tr>
                        <th>郵便番号</th>
                        <td><%= @customer.postal_code %></td>
                    </tr>
                    <tr>
                        <th>住所</th>
                        <td><%= @customer.address %></td>
                    </tr>
                    <tr>
                        <th>電話番号</th>
                        <td><%= @customer.tel %></td>
                    </tr>
                    <tr>
                        <th>メールアドレス</th>
                        <td><%= @customer.email %></td>
                    </tr>
                </table>

                <%= link_to '編集する', edit_admin_customer_path(@customer), class:"btn btn-primary
                glyphicon glyphicon-wrench btn-lg" %>
                <%= link_to '注文履歴一覧を見る',admin_path(@customer),class:"btn btn-primary glyphicon btn-lg" %>
            </div>
        </div>
    </body>
</html>

app/views/admin/customers/top.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>ながのCAKE 管理画面</title>
    </head>
    <body>
        <div class="container">
            <div class="col-md-8 col-md-offset-4">

        <h2>本日の注文件数
            <%=link_to @order_counts.count ,admin_period_index_path%>
        件</h2>
    </body>
</html>