config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    get 'searchwindows/index',as: "search"
  end
  namespace :admin do
    get 'searchwindow/index'
    get 'searchwindow/search'
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
  }

  scope module: :customer do
    resources :addresses, except:[:new,:show]
  end

  scope module: :customer do
    resources :cart_items, except:[:show,:new]
    get 'cart_items/confirm'
  end

  scope module: :customer do
    resources :cart_items, except:[:show,:new]
    delete 'cart_items', to: 'cart_items#all_destroy'
  end

  scope module: :customer do
    get 'orders/thanks', to: 'orders#thanks',as: 'orders_thanks'
    resources :orders, only:[:show,:index,:create]
  end

  scope module: :customer do
    resources :items, only:[:show]
  end

  scope module: :customer do
    get 'customers/with_draw' => "customers#with_draw"
    resources :customers, only:[:show,:edit,:update,:destroy]
  end

  scope module: :home do
    root 'homes#top'
    get 'homes/about'
    get 'homes/category/:id' => "homes#category",as:'category'
  end

  namespace :admin do
    get 'period_index' => 'orders#period_index'
    get 'customer_index/:id' => 'orders#customer_index'
    resources :orders, except:[:new,:show,:create,:destroy] do
      
      patch 'item_update/:order_item_id' => 'orders#item_update', as: 'update'
      put 'item_update/:order_item_id' => 'orders#item_update'
    end
  end

  namespace :admin do
    resources :items
  end

  namespace :admin do
    resources :customers, only:[:index,:show,:edit,:update]
    get 'customer/top' => "customers#top"
  end

  namespace :admin do
    resources :categories
  end

  namespace :admin do
  get "searches/" => "searchwindows#index", as: "search"
  end

  namespace :admin do
  get "customer/searches/" => "customersearches#index"
  end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer

	def postal_code_address_full_name
		self.postal_code + " " + self.address+ " " + self.full_name
	end

	validates :postal_code, format: { with: /\A[0-9０-９]+\z/, message: "を数値で入力してください"}
  validates :address, presence: true
  validates :full_name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :customer
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
    validates :sweets_name, presence: true
	validates :category_status, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :addresses
	has_many :cart_items
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を漢字、ひらがな、カタカナで入力してください" }
  validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を漢字、ひらがな、カタカナで入力してください"}
  validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "をカタカナで入力してください"}
  validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "をカタカナで入力してください"}
  validates :postal_code, format: { with: /\A[0-9０-９]+\z/,  message: "を数値で入力してください"}
  validates :address, presence: true
  validates :tel, format: { with: /\A[0-9０-９]+\z/, message: "を数値で入力してください"} 
  # validates :customer_status, inclusion: {in: [true, false]}
  def active_for_authentication?
    super && customer_status?
  end
  def inactive_message
    customer_status? ? super : :with_draw
  end
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :order_items
	has_many :cart_items
	belongs_to :category
	attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :customer

	enum order_status: {
		wait:         0,
		verification: 1,
		creating:     2,
		shipping:     3,
		shipped:      4,
	}, _prefix: true #接尾辞

	enum pay_method: {
		credit:         0,
		bank:           1,
	}, _prefix: true #接尾辞
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :item
	belongs_to :order
	enum create_status: {
		ipossible:0,
		wait:     1,
		create:   2,
		completed:3
	}, _prefix: true #接尾辞
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:tel,:customer_status])
  end
end

app/controllers/home/homes_controller.rb
class Home::HomesController < ApplicationController
  def top
    @items = Item.all
    @categories = Category.all
  end

  def about
  end

  def category
    @category = Category.find(params[:id])
    @category_item = Item.where(category_id: params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searchwindow_helper.rb
module Admin::SearchwindowHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/home/homes_helper.rb
module Home::HomesHelper
end

app/views/layouts/admin/adminapplications.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <script src="https://kit.fontawesome.com/0038349627.js" crossorigin="anonymous"></script>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track':
        'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar" style="background-color: yellow;">
            <div class="navar-header">
                <h1><%= link_to("ながのCAKE", admin_customer_top_path, {class: "navbar-brand"}) %></h1>
                <div class="nav navbar-nav header-items">
                    <% if admin_signed_in? %>
                        <li class="active">
                            <%= link_to("商品一覧", admin_items_path, {class: "active"}) %></li>
                        <li class="active">
                            <%= link_to("会員一覧", admin_customers_path, {class: "active"}) %></li>
                        <li class="active">
                            <%= link_to("注文履歴一覧", admin_orders_path(rute: 1), {class: "active"})%></li>
                        <li class="active">
                            <%= link_to("ジャンル管理", admin_categories_path, {class: "active"})%></li>
                        <li class="active">
                            <%= link_to("ログアウト", destroy_admin_session_path, {method: :delete, class:
                            "active"}) %></li>
                </div>
                <div class="searchrwindow %">
                    <%= form_with(url: admin_customer_searches_path, method: :get, local: true) do %>
                    <%= text_field_tag :search, placeholder="会員名を入力" %>
                    <%= submit_tag 'Search' %>
                    <% end %>
                    <%= form_with(url: admin_search_path, method: :get, local: true) do %>
                    <%= text_field_tag :search, placeholder="商品名を入力"%>
                    <%= submit_tag 'Search' %>
                    <% end %>
                </div>
            <% end %>
            </div>
        </nav>
        <%= yield %>
    </body>
</html>

app/views/layouts/admins/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mr2Cakeshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <h2 class="navbar-brand" href="#">ながのCAKE</h2>
        </div>
        </nav>
  </header>
    <%= yield %>
  </body>
</html>